import "@radix-ui/themes/styles.css";
import "./theme-config.css";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Container, Theme, ThemePanel } from "@radix-ui/themes";
import NavBar from "./Navbar";
import DarkModeContext from "./components/DarkModeProvider";
import { TaskProvider } from "./providers/TaskProvider";

const inter = Inter({
  subsets: ["latin"],
  // display: "swap",
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Request MS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.variable}>
        <DarkModeContext>
          <TaskProvider>
            {/* <Theme> */}
            <Theme accentColor="iris" radius="none">
              <NavBar />
              <main className="px-5">{children}</main>
              {/* <ThemePanel /> */}
            </Theme>
          </TaskProvider>
        </DarkModeContext>
      </body>
    </html>
  );
}
